steps:
  - name: 'golang:1.16.12-alpine'
    entrypoint: 'go'
    dir: src
    args: ['vet', './...']

  - name: 'golang:1.16.12-alpine'
    entrypoint: 'go'
    dir: 'src'
    args: ['test', '-v', './...']

options:
  env:
    - 'CGO_ENABLED=0'
