steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: '/bin/ash'
    args:
      [
        '-c',
        'gcloud secrets versions access latest --secret=api-server-secrets > secrets.yaml',
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: 'gcloud'
    args: ['app', 'deploy', '--quiet']

options:
  env:
    - 'CGO_ENABLED=0'
