version: '3'

services:
  web:
    build: .
    environment:
      DB_USER: harvest
      DB_PASS: FM5fX|jt(gdv-N%L
      DB_INSTANCE_CONNECTION_NAME: harvest_mysql_1:3306
      DB_NAME: mr_president
      ENVIRONMENT: dev
      MODE: debug
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: /bin/ash -c "./database/wait_mysql.sh"
    stdin_open: true
    tty: true
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: '&2dwn*8VSBj7WTU_'
    image: mysql:8
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
